stages:
  - test
  - build
language: node_js
services:
  - mongodb
  - docker
node_js:
- '10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
  - npm update
install:
  - npm install
jobs:
  include:
    - stage: test
    script:
      - npm run test
    - stage: build
    script:
      - docker build -t diogo8machado/meetapp-api .
