jobs:
  include:
    - stage: test
      language: node_js
      services:
        - mongodb
      node_js:
      - '10'
      branches:
        only:
        - master
      cache:
        directories:
        - node_modules
      before_install:
      - npm update
      install:
        - npm install
      script:
        - npm run test
    - stage: deploy
      services:
        - docker
      script:
        - docker build -t diogo8machado/meetapp-api .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push diogo8machado/meetapp-api
        - echo "$private_ssh" >> ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh root@diogomachado.site "docker pull diogo8machado/meetapp-api:latest && docker service update --image diogo8machado/meetapp-api:latest	meetapp_backend"
