jobs:
  include:
    - stage: deploy
      services:
        - docker
      before_install:
        - openssl aes-256-cbc -K $encrypted_9eee3a09da4e_key -iv $encrypted_9eee3a09da4e_iv -in id_rsa.enc -out /tmp/git_deploy_key -d
        - chmod 600 /tmp/git_deploy_key
        - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
        - eval "$(ssh-agent -s)"
        - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
      script:
        - ssh-keyscan diogomachado.site >> $HOME/.ssh/known_hosts
        - cat  ~/.ssh/id_rsa
        - sshpass -p passphrase ssh-add ~/.ssh/id_rsa
        - ssh root@diogomachado.site "docker pull diogo8machado/meetapp-api:latest && docker service update --image diogo8machado/meetapp-api:latest	meetapp_backend"
