jobs:
  include:
    - stage: deploy
      services:
        - docker
      script:
        - echo "$private_ssh" >> ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh -o "CheckHostIP=no" root@diogomachado.site "docker pull diogo8machado/meetapp-api:latest && docker service update --image diogo8machado/meetapp-api:latest	meetapp_backend"
