version: '3.7'
services:
  backend:
    # or image: diogo8machado/regim
    build: .
    ports:
      - 3333:3333
    environment:
      NODE_ENV: production
      APP_SECRET: test
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: docker
      DB_NAME: meetapp

    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: meetapp
    volumes:
      - pg_data_regim:/var/lib/postgresql/data
  mongo:
    image: mongo
  redis:
    image: redis
volumes:
  pg_data_regim:
